### ISSUE TITLE
All Joycons But Last Has 1 Second Delays

### ISSUE THREAD

**Issue by EdTheDog** [mfosse/JoyCon-Driver#42]
If more info needed pls specify

**Comment by mfosse** [comment]
@EdTheDog is it consistently laggy? does it only happen under certain conditions? how many joycons are you connecting?

**Comment by EdTheDog** [comment]
I am connecting 2 joycons but I have tried 3 and only the last joycon connected responds fast. It seems to happen no matter what I do. Yes, it is consistent. It's always 1 second not more not less. So far I have tried Restarting my computer, connecting the joycon back to the switch and then connecting them back to my PC, and I have also tried updating both the joycon driver and Vjoy. I have checked my pc ram and CPU which are both fine so I don't seem to be paging the data. Still trying though.

**Comment by EdTheDog** [comment]
Also, I would like to say the work you have been doing is amazing! It is awesome that someone is trying to do this. :)

**Comment by mfosse** [comment]
Oh, I think I know exactly what the problem is, I'll try to fix it around 4

**Comment by EdTheDog** [comment]
Quick Question, What do you mean by 4? As at Four O'clock? And if so what time zone? I'm PTS and it's 1:30 at the time of this message. Anyway, I hope it's working out so far!

**Comment by EdTheDog** [comment]
Hello?

**Comment by mfosse** [comment]
Sorry lol, I meant 4pm EST (which it's way past) I ended up being busy with other stuff but will work on it now

**Comment by EdTheDog** [comment]
OK Thank you Sorry for bothering you. :) Again I think this is incredible!

**Comment by EdTheDog** [comment]
BTW where do I donate?

**Comment by mfosse** [comment]
it's at the end of the readme: https://github.com/mfosse/JoyCon-Driver
the latest update should fix the bug.

**Comment by EdTheDog** [comment]
Thank you so much! Will try now! But again I want to show my support! Is there a place to donate? If not then you should make one! :)

**Comment by mfosse** [comment]
thanks! :D

**Comment by EdTheDog** [comment]
Unfortunately, My Recent attempts have not been going well. The issue still persists on my computer. Reinstalling Vjoy now. Hmmm....

**Comment by EdTheDog** [comment]
Did more investigating and found out that it doesn't seem to be your program. Right now I'm trying to set up a game the has mouse and button controls and only the joycon controlling the mouse needs to be analog. And since the last joycon connected works fine the Ill only connect that one to the program and it will work, right? Well, I ran the program with (R) joycon and it worked fine then connected the (L) joycon to do the buttons. But then the (R) joycon started going slow even tho I didn't refresh the program! So It seems to be something else. Anyway, that's all I have right now, and at the moment you're probably sleeping so... yeah. Anyway, hope this info might help.

**Comment by EdTheDog** [comment]
Hello again, Just wanted to confirm that the Joycon Driver is working correctly on your computer?

**Comment by mfosse** [comment]
Idk I didn't test it lol, I'd look into it but I'm packing/about to go home for thanksgiving

**Comment by mfosse** [comment]
I just made some changes that I thought would fix the issue (without testing it) if it still isn't working, it probably isn't your setup / PC

**Comment by EdTheDog** [comment]
Ok! Anyway, I hope you have fun at Thanksgiving!

**Comment by EdTheDog** [comment]
Omg, I really wish this would work. I keep doing it over and over again because I just can't wait. Honestly, if you get the delays to work you could sell this is an online product for like 20 dollars. I would save up to buy that for sure. I don't want to pressure you or anything but... I CAN'T WAIT :D

**Comment by EdTheDog** [comment]
Any updates so far? If you're busy It would be kind to notify for how long.

**Comment by mfosse** [comment]
I'm on break rn and don't have access to my desktop, I won't be back until tomorrow, but I have to and will probably be busy until wednesday.

**Comment by EdTheDog** [comment]
OK Thank you for the information :)

**Comment by mfosse** [comment]
this should be fixed now

**Comment by EdTheDog** [comment]
Thank you for putting up with me and thanks for helping me :)
